backend:
  name: git-gateway
  branch: main  # Change this if you're using a different branch

media_folder: "static/uploads" # Where images are stored
public_folder: "/uploads"

collections:
  - name: "post"
    label: "News Articles"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Authors", name: "authors", widget: "list", default: ["admin"] }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["Research"] }
      - { label: "Body", name: "body", widget: "markdown" }
